spring.datasource.url=jdbc:sqlite:smartcampus.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.security.oauth2.client.registration.google.client-id=775783629102-897cm985476ltpvi3k9msj8ml1cqrkut.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
