
spring.data.mongodb.auto-index-creation=true
spring.security.oauth2.client.registration.google.client-id=775783629102-897cm985476ltpvi3k9msj8ml1cqrkut.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.main.allow-circular-references=true