
spring.data.mongodb.auto-index-creation=true
spring.security.oauth2.client.registration.google.client-id=775783629102-897cm985476ltpvi3k9msj8ml1cqrkut.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.main.allow-circular-references=true
spring.data.mongodb.database=smart_campus_db 
spring.data.mongodb.uri=mongodb://localhost:27017/smart_campus_db

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000